include:
  - project: flywheel-io/scientific-solutions/etc/sse-qa-ci
    ref: 653839a2f731d8af64ae94780ef5382b6e9ae7a0
    file: ci/gear-exchange.yml
variables:
  PYTEST_COV_FAIL_UNDER: 0  # Set pytest coverage to 0
  DEBUG: "9"