include:
  - project: flywheel-io/scientific-solutions/etc/sse-qa-ci
    ref: ef4fcd765545acc32720a78cdd12f5819243ee1a
    file: ci/gear-exchange.yml

variables:
  CACHE_KEY: cache
  CACHE_CLEAR: ""
  GIT_DEPTH: 100000

publish:exchange-docker:
  extends: .publish:exchange-docker
  cache:
    key: $CACHE_KEY
    paths: [ .cache ]
  rules:
    - if: "$CI_PIPELINE_SOURCE =~ /^(merge_request_event|web|api)$/ && $MANIFEST_VAL =~ /^[a-zA-Z0-9_-]+\\/[a-zA-Z0-9_.:-]+$/ && $CI_COMMIT_BRANCH == 'GEAR-2518-exchange-CI-plugin'"
      exists:
        - "gears/**/*"
      changes:
        paths:
          - "gears/**/*"
        compare_to: "master"
      when: always
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#      when: never
#    - if: $CI_COMMIT_BRANCH == "GEAR-2518-exchange-CI-plugin"
#    - exists:
#        - "gears/vistalab/*.json"
#    - changes:
#        - "gears/vistalab/*.json"
#    - changes:
#        - "gears/vistalab/*/*.json"
#  rules:
#    # TODO change this to DEFAULT_BRANCH when merged
##    - changes:
##        - "./gears/*"
##      if: $CI_PIPELINE_SOURCE == "merge_request_event"
#    - if: $CI_COMMIT_BRANCH == "GEAR-2518-exchange-CI-plugin"
#      # only run when there are changes in the gears directory
#      changes:
#        - gears/vistalab/*.json
  before_script:
    - echo "nothing"
  script:
    - echo "test"
    # TODO move changes to the actual shell script
#    - ./bin/process-manifests-mod.sh