include:
  - project: flywheel-io/scientific-solutions/etc/sse-qa-ci
    ref: ef4fcd765545acc32720a78cdd12f5819243ee1a
    file: ci/gear-exchange.yml

variables:
  CACHE_KEY: cache
  CACHE_CLEAR: ""
  GIT_DEPTH: 100000

publish:exchange-docker:
  extends: .publish:exchange-docker
  cache:
    key: $CACHE_KEY
    paths: [ .cache ]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      exists:
        - "gears/**/*"
      changes:
        paths:
          - "gears/**/*"
#        compare_to: "master"
      when: always
  before_script:
    - echo "nothing"
  script:
    - echo "test"
    # TODO move changes to the actual shell script
#    - ./bin/process-manifests-mod.sh